### ISSUE TITLE
getting pending response

### ISSUE THREAD

**Issue by zarif59** [kofta999/we-toolkit#2]
I ran the example usage code and do console.log for usage and balance. I keep getting ` Promise { <pending> }`. My login seem to be no error. Please help.

**Comment by kofta999** [comment]
Sorry my bad, I have never imagined anyone would use that package lmao

All these functions are async so you need to `await` them for the promise to be resolved

I've updated the example in readme to show that

**Comment by zarif59** [comment]
thank you for the update. i manage to get response from the api. but i need to add `"type": "module"` in the `package.json` file first. btw, im planning to use this package together with telegram bot to sent daily usage to my telegram group together with my friend. we are living together and i getting annoying as they always keep asking me about the usage. thanks again for the package .

**Comment by kofta999** [comment]
The telegram bot is such a great idea imo, I was thinking about doing something similar too but was too lazy to do it.

I'd really like to try it out when you're done of it!

Also if you've any suggestions to that package please tell me

**Comment by zarif59** [comment]
I done integrated we-toolkit with telegram bot. Have a look at my [repo ](https://github.com/zarif59/we-toolkit-telegram).
